steps:
  - label: "🏗️ Setup Dependencies"
    command: |
      set -euxo pipefail
      echo "--- Download and install Go"
      if ! command -v go &> /dev/null; then
        wget -O go.tar.gz https://go.dev/dl/go1.24.7.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go.tar.gz
        rm go.tar.gz
      fi
      export PATH=$PATH:/usr/local/go/bin
      go version

      echo "--- Download Cloud Hypervisor binary"
      if ! command -v cloud-hypervisor &> /dev/null; then
        wget -O cloud-hypervisor https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v48.0/cloud-hypervisor
        chmod +x cloud-hypervisor
        sudo mv cloud-hypervisor /usr/local/bin/
      fi
      cloud-hypervisor --version

  - label: "🏗️ Build & Unit Tests"
    command: |
      set -euxo pipefail
      export PATH=$PATH:/usr/local/go/bin
      echo "--- Go environment"
      go version
      go env

      echo "--- Dependencies and linting"
      go mod tidy
      go vet ./...

      echo "--- Unit tests"
      go test -count=1 -race ./...

      echo "--- Build binary"
      go build -v ./...

  - label: "🔬 Cloud Hypervisor Integration Test"
    command: |
      set -euxo pipefail
      export PATH=$PATH:/usr/local/go/bin

      echo "--- Verify Cloud Hypervisor binary"
      cloud-hypervisor --version

      echo "--- Check network bridge"
      ip link show ${BRIDGE:-br0} || (echo "Bridge ${BRIDGE:-br0} not found" && exit 1)

      echo "--- Verify test artifacts exist"
      ls -la ${KERNEL_PATH:-/root/vmlinux-normal}
      ls -la ${INITRD_PATH:-/root/raiin-fc.cpio.gz}
      ls -la ${ROOTFS_PATH:-/root/rootfs.img}

      echo "--- Integration tests"
      sudo -E env \
        PATH="$PATH" \
        KERNEL_PATH="${KERNEL_PATH:-/root/vmlinux-normal}" \
        INITRD_PATH="${INITRD_PATH:-/root/raiin-fc.cpio.gz}" \
        ROOTFS_PATH="${ROOTFS_PATH:-/root/rootfs.img}" \
        CH_BIN="cloud-hypervisor" \
        BRIDGE="${BRIDGE:-br0}" \
        go test -v -count=1 ./...

env:
  KERNEL_PATH: "/root/vmlinux-normal"
  INITRD_PATH: "/root/raiin-fc.cpio.gz"
  ROOTFS_PATH: "/root/rootfs.img"
  CH_BIN: "/usr/bin/cloud-hypervisor"
  BRIDGE: "br0"

agents:
  # Run on the agent with Cloud Hypervisor capabilities
  queue: "default"