// Copyright IBM Corp. 2024, 2026
// SPDX-License-Identifier: MPL-2.0

package disks

import (
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/nomad-driver-virt/internal/convert"
	"github.com/hashicorp/nomad-driver-virt/internal/errs"
	"github.com/hashicorp/nomad-driver-virt/storage"
	"github.com/hashicorp/nomad-driver-virt/storage/image_tools"
	"github.com/hashicorp/nomad/helper/pointer"
	"github.com/hashicorp/nomad/plugins/drivers"
	"github.com/hashicorp/nomad/plugins/shared/hclspec"
)

var (
	ErrDisallowedPath  = fmt.Errorf("%w: access to path is not allowed", errs.ErrInvalidConfiguration)
	ErrPathNotFound    = fmt.Errorf("%w: path not found", errs.ErrInvalidConfiguration)
	ErrNoPrimary       = fmt.Errorf("%w: no primary disk defined", errs.ErrInvalidConfiguration)
	ErrMultiplePrimary = fmt.Errorf("%w: multiple primary disks defined", errs.ErrInvalidConfiguration)

	configSpec = hclspec.NewBlockSet("disk", hclspec.NewObject(map[string]*hclspec.Spec{
		"pool":      hclspec.NewAttr("pool", "string", false),
		"volume":    hclspec.NewAttr("volume", "string", false),
		"devname":   hclspec.NewAttr("devname", "string", false),
		"driver":    hclspec.NewAttr("driver", "string", false),
		"kind":      hclspec.NewAttr("kind", "string", false),
		"bus_type":  hclspec.NewAttr("bus_type", "string", false),
		"format":    hclspec.NewAttr("format", "string", false),
		"primary":   hclspec.NewAttr("primary", "bool", false),
		"size":      hclspec.NewAttr("size", "string", false),
		"chained":   hclspec.NewAttr("chained", "bool", false),
		"read_only": hclspec.NewAttr("read_only", "bool", false),
		"sparse":    hclspec.NewAttr("sparse", "bool", false),
		"source": hclspec.NewBlock("source", false, hclspec.NewObject(map[string]*hclspec.Spec{
			"format": hclspec.NewAttr("format", "string", false),
			"image":  hclspec.NewAttr("image", "string", false),
			"volume": hclspec.NewAttr("volume", "string", false),
		})),
	}))
)

const (
	BusTypeDefault  = storage.BusTypeVirtio
	DiskKindDefault = storage.DiskKindDisk

	identifierPrefix = "nmdsrc"
)

type DiskValidator interface {
	// ValidateDisk inspects a disk to determine if it defines
	// a valid disk.
	ValidateDisk(disk *Disk) error
}

// NewDisks returns a new disk collection.
func NewDisks() Disks {
	return make(Disks, 0)
}

// ValidationOptions are used when validating the disks configuration.
type ValidationOptions struct {
	AllowedPaths []string // Absolute paths on host allowed for image files
}

// AllowedPath checks if the provided path is within the defined allowed paths
// TODO: opinion on symlnks?
func (v ValidationOptions) AllowedPath(path string) bool {
	var err error
	if !filepath.IsAbs(path) {
		if path, err = filepath.Abs(path); err != nil {
			return false
		}
	}

	for _, dir := range v.AllowedPaths {
		root, err := os.OpenRoot(dir)
		if err != nil {
			continue
		}
		if !strings.HasSuffix(dir, string(filepath.Separator)) {
			dir += string(filepath.Separator)
		}

		if len(dir) > len(path) {
			continue
		}

		if !strings.EqualFold(dir, path[0:len(dir)]) {
			continue
		}

		checkPath := path[len(dir):]
		info, err := root.Stat(checkPath)
		if err != nil {
			continue
		}

		// If it's a file, then it's valid
		return !info.IsDir()
	}

	return false
}

// Disks contain a list of disk attachment configurations
type Disks []*Disk

// Disk contains configuration information for a disk attachment
type Disk struct {
	Devname    string  `codec:"devname"`   // Device name. Value is autogenerated if unset.
	Driver     string  `codec:"driver"`    // Specify custom driver for disk if applicable. Default is provider defined.
	Kind       string  `codec:"kind"`      // Kind of disk defined: cdrom, lun, disk.
	BusType    string  `codec:"bus_type"`  // Bus type of the disk: virtio, ide, sata, scsi.
	Primary    bool    `codec:"primary"`   // Primary disk to be booted (only one allowed).
	VolumeName string  `codec:"volume"`    // Nomad volume to use as this disk.
	Format     string  `codec:"format"`    // Format of the disk: raw, qcow2, etc.
	Size       string  `codec:"size"`      // Size of the volume in bytes or size followed by suffix (10GB or 10GiB).
	Chained    bool    `codec:"chained"`   // Volume should be chained to source ("thin" copy).
	Sparse     *bool   `codec:"sparse"`    // Volume should be sparsely populated if supported.
	ReadOnly   bool    `codec:"read_only"` // Disk is readonly.
	Source     *Source `codec:"source"`    // Source image for new volume.
	Pool       string  `codec:"pool"`      // Name of pool to store disk volume.

	Volume          *storage.Volume // Used internally, not exposed to config
	blockDevicePath string          // Path to block device for nomad volume
}

// IsNomadVolume returns if this disk is backed by a Nomad volume.
func (d *Disk) IsNomadVolume() bool {
	return d.VolumeName != ""
}

// ValidateNomadVolume validates the disk
func (d *Disk) ValidateNomadVolume() error {
	if !d.IsNomadVolume() {
		return nil
	}

	var mErr *multierror.Error

	if d.Format != "" && d.Format != storage.DiskFormatRaw {
		mErr = multierror.Append(mErr,
			fmt.Errorf("%w: format cannot be set when using Nomad volume", errs.ErrInvalidConfiguration))
	}
	if d.Size != "" {
		mErr = multierror.Append(mErr,
			fmt.Errorf("%w: size cannot be set when using Nomad volume", errs.ErrInvalidConfiguration))
	}
	if d.Sparse != nil {
		mErr = multierror.Append(mErr,
			fmt.Errorf("%w: sparse cannot be set when using Nomad volume", errs.ErrInvalidConfiguration))
	}
	if d.Pool != "" {
		mErr = multierror.Append(mErr,
			fmt.Errorf("%w: pool cannot be set when using Nomad volume", errs.ErrInvalidConfiguration))
	}
	if d.Chained {
		mErr = multierror.Append(mErr,
			fmt.Errorf("%w: chained cannot be set when using Nomad volume", errs.ErrInvalidConfiguration))
	}
	if d.Source != nil {
		if d.Source.Volume != "" {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%w: source.volume cannot be set when using Nomad volume", errs.ErrInvalidConfiguration))
		}
	}

	if d.blockDevicePath == "" {
		mErr = multierror.Append(mErr,
			fmt.Errorf("%w: missing Nomad volume mount configuration", errs.ErrInvalidConfiguration))
	}

	return mErr.ErrorOrNil()
}

// Source describes the source of the disk
type Source struct {
	Image  string `codec:"image"`  // Image file from which to generate new volume or readonly disk.
	Format string `codec:"format"` // Format of the source image. Setting this will prevent inspecting the file.
	Volume string `codec:"volume"` // Existing volume from which to generate new volume.

	identifier string // Unique source identifier generated internally.
}

func (s *Source) Equal(rhs *Source) bool {
	if s == nil && rhs == nil {
		return true
	}
	if s == nil || rhs == nil {
		return false
	}

	return *s == *rhs
}

// ApplyCloudInit will add a disk entry as a cdrom for cloud-init
// TODO: adjust this to return errors so stat errors can be surfaced.
func (d Disks) ApplyCloudInit(isoPath string) Disks {
	if d == nil {
		d = Disks{}
	}

	newDisk := &Disk{
		BusType: storage.BusTypeIde,
		Kind:    storage.DiskKindCdrom,
		Format:  "raw",
		Source: &Source{
			Format: "raw",
			Image:  isoPath,
		},
		ReadOnly: true,
	}

	return append(d, newDisk)
}

// CompatAddImage supports deprecated task configuration
func (d Disks) CompatAddImage(image string, size int64, thinCopy bool) Disks {
	if d == nil {
		d = Disks{}
	}

	newDisk := &Disk{
		BusType: storage.BusTypeVirtio,
		Primary: true,
		Source: &Source{
			Image: image,
		},
		Size:    fmt.Sprintf("%dMiB", size),
		Chained: thinCopy,
	}

	// For proper compatibility, set the format to qcow2
	// if making a thin copy.
	if thinCopy {
		newDisk.Format = storage.DiskFormatQcow2
	}

	return append(d, newDisk)
}

// ResolveImages normalizes paths in the file disk configurations
func (d Disks) ResolveImages(dirs []string) {
	if d == nil {
		return
	}

	for _, disk := range d {
		if disk.Source == nil {
			continue
		}

		if disk.Source.Image != "" && !fileExists(disk.Source.Image) && filepath.IsLocal(disk.Source.Image) {
			for _, dir := range dirs {
				if dir == "" {
					continue
				}
				testPath := filepath.Join(dir, disk.Source.Image)
				if fileExists(testPath) {
					disk.Source.Image = testPath
				}
			}
		}
	}
}

// ApplyMounts updates any disk entries that define a VolumeName with
// the required information for the associated mount config.
func (d Disks) ApplyMounts(mounts []*drivers.MountConfig) error {
	if d == nil {
		return nil
	}

	// Make a map of the valid mounts configs that can be used for Nomad volumes
	// to allow for quick lookups below.
	mnts := make(map[string]*drivers.MountConfig)
	for _, m := range mounts {
		// TODO: This can be uncommented once https://github.com/hashicorp/nomad/pull/27710
		// has been merged and released.
		// if m.RequestName != "" {
		// 	mnts[m.RequestName] = m
		// }

		// NOTE: Versions of Nomad < 2.0 do not include the RequestName
		// in the mount config information so the path is used instead
		// for matching.
		if strings.HasPrefix(m.TaskPath, "/dev/") {
			mnts[m.TaskPath] = m
		}
	}

	for _, disk := range d {
		if !disk.IsNomadVolume() {
			continue
		}

		m, ok := mnts[disk.VolumeName]
		if !ok {
			continue
		}

		disk.blockDevicePath = m.HostPath
		disk.ReadOnly = m.Readonly
		disk.Format = storage.DiskFormatRaw // block device will always be raw

		// If a device name is set directly on the disk, then it is the value
		// used. Otherwise extract the device name from the task path.
		if disk.Devname == "" {
			disk.Devname = filepath.Base(m.TaskPath)
		}
	}

	return nil
}

// Prepare will prepare the disks configuration for validation and generation. It
// will fill in empty values with defaults where applicable and perform image
// conversions or parent volume creations where needed.
func (d Disks) Prepare(s storage.Storage) error {
	if d == nil {
		return nil
	}

	validPrimaryDisks := []*Disk{}
	var primaryFound bool
	for _, disk := range d {
		// Default disk driver will come from the storage implementation.
		if disk.Driver == "" {
			disk.Driver = s.DefaultDiskDriver()
		}

		// Default the kind of disk.
		if disk.Kind == "" {
			disk.Kind = DiskKindDefault
		}

		// If the kind of disk is a cdrom, set the bus to IDE, otherwise.
		// just default to virtio.
		if disk.BusType == "" {
			if disk.Kind == storage.DiskKindCdrom {
				disk.BusType = storage.BusTypeIde
			} else {
				disk.BusType = BusTypeDefault
			}
		}

		// If a device name has not already been provided, generate one.
		if disk.Devname == "" {
			disk.Devname = d.generateDevname(disk, s)
		}

		// If a source image is set, attempt to determine its format if not set.
		if disk.Source != nil && disk.Source.Image != "" && disk.Source.Format == "" {
			sfmt, err := s.ImageHandler().GetImageFormat(disk.Source.Image)
			if err != nil {
				return err
			}
			disk.Source.Format = sfmt
		}

		if disk.Primary {
			primaryFound = true
		}

		if disk.Kind != storage.DiskKindCdrom {
			validPrimaryDisks = append(validPrimaryDisks, disk)
		}

		// If the disk is backed by a Nomad volume, nothing more to do.
		if disk.IsNomadVolume() {
			continue
		}

		// Load up the target pool of the disk.
		var pool storage.Pool
		var err error
		if disk.Pool != "" {
			pool, err = s.GetPool(disk.Pool)
		} else {
			pool, err = s.DefaultPool()
		}
		if err != nil {
			return err
		}

		// Get the default format for the disk from the target pool if no
		// format is provided
		if disk.Format == "" {
			disk.Format = pool.DefaultImageFormat()
		}

		// If the disk is chained generate the identifier if needed and
		// create the parent volume if it does not exist.
		if disk.Source != nil && disk.Source.Image != "" {
			if disk.Chained {
				if disk.Source.identifier == "" {
					var err error
					disk.Source.identifier, err = generateIdentifier(disk.Source.Image, disk.Format)
					if err != nil {
						return err
					}
				}

				vol, err := pool.GetVolume(disk.Source.identifier)
				if err != nil {
					if !errors.Is(err, errs.ErrNotFound) {
						return err
					}

					// If the source image isn't in the disk format, convert it.
					if disk.Source.Format != disk.Format {
						disk.Source.Image, err = convertImage(s.ImageHandler(), disk.Source.Image, disk.Source.Format, disk.Format)
						if err != nil {
							return err
						}
						defer os.Remove(disk.Source.Image)
					}

					size, err := s.ImageHandler().GetImageSize(disk.Source.Image)
					if err != nil {
						return err
					}

					parentOpts := storage.Options{
						Sparse: true,
						Target: storage.Target{
							Format: disk.Format,
						},
						Source: storage.Source{
							Path: disk.Source.Image,
						},
						Size: size,
					}

					// Create the parent volume.
					vol, err = pool.AddVolume(disk.Source.identifier, parentOpts)
					if err != nil {
						return err
					}
				}

				// Remove the source image and set the source
				// volume to the parent.
				disk.Source.Volume = vol.Name
				disk.Source.Image = ""

				// If the size was not set for the disk, set it to the
				// parent volume size since we have the volume available.
				if disk.Size == "" {
					disk.Size = fmt.Sprintf("%d", vol.Size)
				}
			} else if disk.Format != disk.Source.Format {
				// Convert the image if the source format doesn't match the disk.
				dst, err := convertImage(s.ImageHandler(), disk.Source.Image, disk.Source.Format, disk.Format)
				if err != nil {
					return err
				}
				disk.Source.Image = dst
				disk.Source.Format = disk.Format
			}
		}

		// If the size is not set and a source is defined, attempt to derive
		// the size from the source.
		if disk.Size == "" && disk.Source != nil {
			// If an image is defined, use the size of the image. This may not be large enough
			// if a format conversion happens, but this is just best effort.
			if disk.Source.Image != "" {
				size, err := s.ImageHandler().GetImageSize(disk.Source.Image)
				if err == nil {
					disk.Size = fmt.Sprintf("%d", size)
				}
			}

			if disk.Source.Volume != "" {
				vol, err := pool.GetVolume(disk.Source.Volume)
				if err != nil {
					return err
				}
				disk.Size = fmt.Sprintf("%d", vol.Size)
			}
		}
	}

	// If no disk was marked as primary, but only one disk has been
	// defined for the virtual machine, automatically mark it as the
	// primary.
	if !primaryFound && len(validPrimaryDisks) == 1 {
		validPrimaryDisks[0].Primary = true
	}

	return nil
}

// Validate validates the disks configurations
func (d Disks) Validate(s storage.Storage, opts ValidationOptions) error {
	var mErr *multierror.Error
	var primaryIdx []string

	for i, disk := range d {
		displayIdx := i + 1 // NOTE: Increment index so disk counts start at 1 for user
		errPrefix := fmt.Sprintf("disk[%d] -", displayIdx)

		if disk.Primary {
			primaryIdx = append(primaryIdx, fmt.Sprintf("%d", displayIdx))
		}

		// Start with checking values that should be set for all disks.
		mErr = multierror.Append(mErr,
			errs.MissingAttribute("bus_type", disk.BusType, errs.WithPrefix(errPrefix)),
			errs.MissingAttribute("kind", disk.Kind, errs.WithPrefix(errPrefix)),
			errs.MissingAttribute("devname", disk.Devname, errs.WithPrefix(errPrefix)),
		)

		// If a source image has been set, check that it exists and it's
		// located at an accessible location.
		if disk.Source != nil && disk.Source.Image != "" {
			if !fileExists(disk.Source.Image) {
				mErr = multierror.Append(mErr,
					fmt.Errorf("%s %w: %s", errPrefix, ErrPathNotFound, disk.Source.Image))
			}
			if !opts.AllowedPath(disk.Source.Image) {
				mErr = multierror.Append(mErr,
					fmt.Errorf("%s %w: %s", errPrefix, ErrDisallowedPath, disk.Source.Image))
			}
			if disk.Source.Volume != "" {
				mErr = multierror.Append(mErr,
					fmt.Errorf("%s %w: source.volume and source.image are mutually exclusive", errPrefix, errs.ErrInvalidConfiguration))
			}

			mErr = multierror.Append(mErr,
				errs.MissingAttribute("source.format", disk.Source.Format, errs.WithPrefix(errPrefix)))
		}

		// If the disk is backed by a Nomad volume, validate that attributes which
		// are not applicable have not been set.
		if disk.IsNomadVolume() {
			if err := disk.ValidateNomadVolume(); err != nil {
				mErr = multierror.Append(mErr, prefixError(errPrefix, err))
			}

			continue
		}

		mErr = multierror.Append(mErr,
			errs.MissingAttribute("format", disk.Format, errs.WithPrefix(errPrefix)),
			errs.MissingAttribute("size", disk.Size, errs.WithPrefix(errPrefix)),
		)

		// If a size for the disk is set, check that the value is a size.
		if disk.Size != "" && !convert.ValidBytesString(disk.Size) {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s %w: size value is not valid - %q", errPrefix, errs.ErrInvalidConfiguration, disk.Size))
		}

		// If the disk is chained, validate that a source is provided.
		if disk.Chained && (disk.Source == nil || (disk.Source.Volume == "" && disk.Source.Image == "")) {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s %w: chained cannot be enabled without a source", errPrefix, errs.ErrInvalidConfiguration))
		}

		// Load the storage pool for this disk. It will be used if the disk source is
		// a volume as well as applying any custom validation if the pool provides it.
		var pool storage.Pool
		var err error
		if disk.Pool != "" {
			pool, err = s.GetPool(disk.Pool)
		} else {
			pool, err = s.DefaultPool()
		}
		if err != nil {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s could not load storage pool - %w", errPrefix, err))
			continue
		}

		// If a source is defined, check that a source value is provided.
		if disk.Source != nil {
			if disk.Source.Volume == "" && disk.Source.Image == "" {
				mErr = multierror.Append(mErr,
					fmt.Errorf("%s %w: disk source must define an image or volume", errPrefix, errs.ErrInvalidConfiguration))
			} else {
				// Check that the size of the disk is sufficient for the source.
				var size uint64
				if disk.Source.Image != "" {
					info, err := os.Stat(disk.Source.Image)
					if err != nil {
						mErr = multierror.Append(mErr,
							fmt.Errorf("%s %w: unable to read source image to determine size: %w", errPrefix, errs.ErrInvalidConfiguration, err))
					} else {
						size = uint64(info.Size())
					}
				} else {
					vol, err := pool.GetVolume(disk.Source.Volume)
					if err != nil {
						mErr = multierror.Append(mErr,
							fmt.Errorf("%s %w: unable to load source volume to determine size: %w", errPrefix, errs.ErrInvalidConfiguration, err))
					} else {
						size = vol.Size
					}
				}

				// Check the size if it's non-zero
				if size > 0 && size > convert.MustToBytes(disk.Size) {
					mErr = multierror.Append(mErr,
						fmt.Errorf("%s %w: size of disk must be equal to or greater than source", errPrefix, errs.ErrInvalidConfiguration))
				}
			}
		}

		// Apply custom validation if provided by the pool.
		validator, ok := pool.(DiskValidator)
		if !ok {
			continue
		}
		if err := validator.ValidateDisk(disk); err != nil {
			mErr = multierror.Append(mErr, prefixError(errPrefix, err))
		}
	}

	if len(primaryIdx) == 0 {
		mErr = multierror.Append(mErr, ErrNoPrimary)
	} else if len(primaryIdx) > 1 {
		mErr = multierror.Append(mErr, fmt.Errorf("%w (disks: %s)",
			ErrMultiplePrimary, strings.Join(primaryIdx, ", ")))
	}

	return mErr.ErrorOrNil()
}

// Generate will generate the storage volumes defined by the disk configuration.
// The name is used for volume naming. Using the task name is ideal.
func (d Disks) Generate(name string, s storage.Storage) error {
	// Generate the volumes for the virtual machine
	for _, disk := range d {
		var pool storage.Pool
		var err error
		var vol *storage.Volume
		volumeName := fmt.Sprintf("%s_%s.img", name, disk.Devname)

		// If the disk is a nomad volume, just prepare it. Otherwise, create the
		// volume in the storage pool.
		if disk.IsNomadVolume() {
			if err := disk.writeNomadVolume(s); err != nil {
				return err
			}

			vol = &storage.Volume{
				Name:   volumeName,
				Format: disk.Format,
				Block:  disk.blockDevicePath,
			}
		} else {
			if disk.Pool != "" {
				if pool, err = s.GetPool(disk.Pool); err != nil {
					return err
				}
			} else {
				if pool, err = s.DefaultPool(); err != nil {
					return err
				}
			}

			if disk.Format == "" {
				disk.Format = pool.DefaultImageFormat()
			}

			if disk.Sparse == nil {
				disk.Sparse = pointer.Of(false)
			}

			opts := storage.Options{
				Chained: disk.Chained,
				Size:    convert.MustToBytes(disk.Size),
				Sparse:  *disk.Sparse,
				Target: storage.Target{
					Format: disk.Format,
				},
			}

			if disk.Source != nil {
				opts.Source = storage.Source{
					Path:   disk.Source.Image,
					Volume: disk.Source.Volume,
				}
			}

			// Now create the new volume.
			vol, err = pool.AddVolume(volumeName, opts)
			if err != nil {
				return err
			}
		}

		// Fill in extra volume information
		vol.Format = disk.Format
		vol.Kind = disk.Kind
		vol.Driver = disk.Driver
		vol.DeviceName = disk.Devname
		vol.BusType = disk.BusType
		vol.Primary = disk.Primary

		// Set the volume for the disk
		disk.Volume = vol
	}

	return nil
}

// Volumes returns the storage volumes for the configured disks
func (d Disks) Volumes() []storage.Volume {
	vols := make([]storage.Volume, 0, len(d))
	for _, disk := range d {
		if disk.Volume != nil {
			vols = append(vols, *disk.Volume)
		}
	}

	return vols
}

// Copy makes a copy of the disks
func (d Disks) Copy() Disks {
	copy := make(Disks, len(d))
	for i, disk := range d {
		dc := *disk
		if disk.Source != nil {
			sc := *disk.Source
			dc.Source = &sc
		}
		if disk.Volume != nil {
			vc := *disk.Volume
			dc.Volume = &vc
		}
		copy[i] = &dc
	}

	return copy
}

// generateDevname generates the device name of the disk.
func (d Disks) generateDevname(disk *Disk, s storage.Storage) string {
	names := []string{}
	for _, existingDisk := range d {
		if existingDisk.Devname != "" {
			names = append(names, existingDisk.Devname)
		}
	}

	return s.GenerateDeviceName(disk.BusType, names)
}

// ConfigSpec returns the HCL specification for the disks configuration
func ConfigSpec() *hclspec.Spec {
	return configSpec
}

// generateIdentifier generates an identifier for a source file based
// on the checksum of the contents
func generateIdentifier(path, format string) (string, error) {
	hash := sha256.New()
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	if _, err := io.Copy(hash, f); err != nil {
		return "", err
	}

	return fmt.Sprintf("%s-%s-%x.img", identifierPrefix, format, hash.Sum(nil)), nil
}

// fileExists checks if a file exists at the path
func fileExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}

	return !info.IsDir()
}

// prepareNomadVolume will copy an image file into the block device provided
// by the nomad volume backing the disk.
func (d *Disk) writeNomadVolume(s storage.Storage) error {
	if d.blockDevicePath == "" {
		return fmt.Errorf("Disk is not backed by Nomad volume")
	}

	// Do nothing if no source is defined
	if d.Source == nil || d.Source.Image == "" {
		return nil
	}

	// Make sure image is in correct format
	img := d.Source.Image
	if d.Format != d.Source.Format {
		rawImg := img + ".raw"
		if err := s.ImageHandler().ConvertImage(img, d.Source.Format, rawImg, d.Format); err != nil {
			return err
		}
		defer os.RemoveAll(rawImg)
		img = rawImg
	}

	// Write the image to the device
	src, err := os.Open(img)
	if err != nil {
		return err
	}
	defer src.Close()

	dst, err := os.OpenFile(d.blockDevicePath, os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer dst.Close()

	if _, err := io.Copy(dst, src); err != nil {
		return err
	}

	return nil
}

// prefixError prepends the prefix to the error. If the error is a multierror.Error
// it will prefix all error messages it contains.
func prefixError(prefix string, err error) error {
	if err == nil {
		return err
	}

	switch err := err.(type) {
	case *multierror.Error:
		var mErr *multierror.Error
		if err == nil {
			return err
		}
		for _, e := range err.Errors {
			if !strings.Contains(e.Error(), prefix) {
				e = fmt.Errorf("%s %w", prefix, e)
			}
			mErr = multierror.Append(mErr, e)
		}
		return mErr
	default:
		return fmt.Errorf("%s %w", prefix, err)
	}
}

// convertImage converts an image file into a different format, creating the
// converted file next to the original.
func convertImage(h image_tools.ImageHandler, src, srcFmt, dstFmt string) (string, error) {
	dir := filepath.Dir(src)
	f, err := os.CreateTemp(dir, fmt.Sprintf("%s-*.%s", filepath.Base(src), dstFmt))
	if err != nil {
		return "", err
	}
	f.Close()

	if err := h.ConvertImage(src, srcFmt, f.Name(), dstFmt); err != nil {
		return "", err
	}

	return f.Name(), nil
}
