// Copyright IBM Corp. 2024, 2025
// SPDX-License-Identifier: MPL-2.0

package disks

import (
	"crypto/sha512"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/nomad-driver-virt/internal/convert"
	"github.com/hashicorp/nomad-driver-virt/storage"
	"github.com/hashicorp/nomad/plugins/shared/hclspec"
)

var (
	ErrMissingAttribute = errors.New("missing required attribute")
	ErrDisallowedPath   = errors.New("access to path is not allowed")
	ErrPathNotFound     = errors.New("path not found")
	ErrNoPrimary        = errors.New("no primary disk defined")
	ErrMultiplePrimary  = errors.New("multiple primary disks defined")

	configSpec = hclspec.NewBlockSet("disk", hclspec.NewObject(map[string]*hclspec.Spec{
		"pool":        hclspec.NewAttr("pool", "string", false),
		"volume_name": hclspec.NewAttr("volume_name", "string", false),
		"devname":     hclspec.NewAttr("devname", "string", false),
		"driver":      hclspec.NewAttr("driver", "string", false),
		"kind":        hclspec.NewAttr("kind", "string", false),
		"bus_type":    hclspec.NewAttr("bus_type", "string", false),
		"format":      hclspec.NewAttr("format", "string", false),
		"primary":     hclspec.NewAttr("primary", "bool", false),
		"size":        hclspec.NewAttr("size", "string", false),
		"chained":     hclspec.NewAttr("chained", "bool", false),
		"read_only":   hclspec.NewAttr("read_only", "bool", false),
		"sparse":      hclspec.NewAttr("sparse", "bool", false),
		"source": hclspec.NewBlock("source", false, hclspec.NewObject(map[string]*hclspec.Spec{
			"format":   hclspec.NewAttr("format", "string", false),
			"image":    hclspec.NewAttr("image", "string", false),
			"snapshot": hclspec.NewAttr("snapshot", "string", false),
			"volume":   hclspec.NewAttr("volume", "string", false),
		})),
	}))
)

const (
	BusTypeVirtio = "virtio"
	BusTypeIde    = "ide"
	BusTypeScsi   = "scsi"
	BusTypeSata   = "sata"

	DiskFormatRaw   = "raw"
	DiskFormatQcow2 = "qcow2"

	DiskKindDisk  = "disk"
	DiskKindLun   = "lun"
	DiskKindCdrom = "cdrom"

	BusTypeDefault  = "virtio"
	DiskKindDefault = "disk"

	identifierPrefix = "nmdsrc"
)

// NewDisks returns a new disk collection.
func NewDisks() Disks {
	return make(Disks, 0)
}

// ValidationOptions are used when validating the disks configuration.
type ValidationOptions struct {
	AllowedPaths []string // Absolute paths on host allowed for image files
}

// AllowedPath checks if the provided path is within the defined allowed paths
// TODO: opinion on symlnks?
func (v ValidationOptions) AllowedPath(path string) bool {
	var err error
	if !filepath.IsAbs(path) {
		if path, err = filepath.Abs(path); err != nil {
			return false
		}
	}

	for _, dir := range v.AllowedPaths {
		root, err := os.OpenRoot(dir)
		if err != nil {
			continue
		}
		if !strings.HasSuffix(dir, string(filepath.Separator)) {
			dir += string(filepath.Separator)
		}

		if len(dir) > len(path) {
			continue
		}

		if !strings.EqualFold(dir, path[0:len(dir)]) {
			continue
		}

		checkPath := path[len(dir):]
		info, err := root.Stat(checkPath)
		if err != nil {
			continue
		}

		// If it's a file, then it's valid
		return !info.IsDir()
	}

	return false
}

// Disks contain a list of disk attachment configurations
type Disks []*Disk

// Disk contains configuration information for a disk attachment
type Disk struct {
	Devname    string  `codec:"devname"`     // Device name (override autogenerated)
	Driver     string  `codec:"driver"`      // Specify custom driver for disk
	Kind       string  `codec:"kind"`        // Specialized kind of disk (cdrom/lun/etc)
	BusType    string  `codec:"bus_type"`    // Bus type of the disk (virtio/ide/etc)
	Primary    bool    `codec:"primary"`     // Primary disk to be booted (only one allowed)
	Format     string  `codec:"format"`      // Format of the disk (raw,qcow2,etc)
	Size       string  `codec:"size"`        // Size of the volume
	Chained    bool    `codec:"chained"`     // Volume should be chained to source ("thin" copy)
	Sparse     bool    `codec:"sparse"`      // Volume should be sparsely populated if supported
	ReadOnly   bool    `codec:"read_only"`   // Disk is readonly
	Source     *Source `codec:"source"`      // Source image for new volume
	Pool       string  `codec:"pool"`        // Name of pool to store disk volume
	VolumeName string  `codec:"volume_name"` // Nomad volume to use as this disk

	Volume *storage.Volume // Used internally, not exposed to config
}

// Source describes the source of the disk
type Source struct {
	Image    string `codec:"image"`    // Image file from which to generate new volume or readonly disk
	Format   string `codec:"format"`   // Format of the source image
	Snapshot string `codec:"snapshot"` // Snapshot from which to generate new volume
	Volume   string `codec:"volume"`   // Existing volume from which to generate new volume

	identifier string
}

// ApplyCloudInit will add a disk entry as a cdrom for cloud-init
func (d Disks) ApplyCloudInit(isoPath string) Disks {
	if d == nil {
		d = Disks{}
	}

	f, err := os.Stat(isoPath)
	if err != nil {
		f = nil
	}

	newDisk := &Disk{
		BusType: BusTypeIde,
		Kind:    DiskKindCdrom,
		Format:  "raw",
		Source: &Source{
			Image: isoPath,
		},
		ReadOnly: true,
	}
	if f != nil {
		newDisk.Size = fmt.Sprintf("%d", f.Size())
	}

	return append(d, newDisk)
}

// CompatAddImage supports deprecated task configuration
func (d Disks) CompatAddImage(image string, size int64, thinCopy bool) Disks {
	if d == nil {
		d = Disks{}
	}

	newDisk := &Disk{
		BusType: BusTypeVirtio,
		Primary: true,
		Source: &Source{
			Image: image,
		},
		Size:    fmt.Sprintf("%dMiB", size),
		Chained: thinCopy,
	}

	// For proper compatibility, set the format to qcow2
	// if making a thin copy.
	if thinCopy {
		newDisk.Format = "qcow2"
	}

	return append(d, newDisk)
}

// ResolveImages normalizes paths in the file disk configurations
func (d Disks) ResolveImages(dirs []string) {
	if d == nil {
		return
	}

	for _, disk := range d {
		if disk.Source == nil {
			continue
		}

		if disk.Source.Image != "" && !fileExists(disk.Source.Image) && filepath.IsLocal(disk.Source.Image) {
			for _, dir := range dirs {
				if dir == "" {
					continue
				}
				testPath := filepath.Join(dir, disk.Source.Image)
				if fileExists(testPath) {
					disk.Source.Image = testPath
				}
			}
		}
	}
}

// SetDefaults will fill in applicable empty values in disk configurations
// with default values
func (d Disks) SetDefaults(s storage.Storage) {
	if d == nil {
		return
	}

	validPrimaryDisks := []*Disk{}
	var primaryFound bool
	for _, disk := range d {
		// Default driver is informed by the storage implementation
		if disk.Driver == "" {
			disk.Driver = s.DefaultDiskDriver()
		}
		if disk.Kind == "" {
			disk.Kind = DiskKindDefault
		}
		// If a source is set, attempt to determine the format if not set
		if disk.Format == "" && disk.Source != nil {
			// Attempt to extract the format from the source
			if disk.Source.Format != "" {
				disk.Format = disk.Source.Format
			} else if disk.Source.Image != "" {
				if iFmt, err := s.ImageHandler().GetImageFormat(disk.Source.Image); err == nil {
					disk.Format = iFmt
					disk.Source.Format = iFmt
				}
			}
		}
		// If no size is set and a source image is available, attempt
		// to use that size
		if disk.Size == "" && disk.Source != nil && disk.Source.Image != "" {
			if info, err := os.Stat(disk.Source.Image); err == nil {
				disk.Size = fmt.Sprintf("%d", info.Size())
			}
		}
		if disk.BusType == "" {
			if disk.Kind == DiskKindCdrom {
				disk.BusType = BusTypeIde
			} else {
				disk.BusType = BusTypeDefault
			}
		}
		if disk.Devname == "" {
			disk.Devname = d.generateDevname(disk, s)
		}

		if disk.Primary {
			primaryFound = true
		}
		if disk.Kind != DiskKindCdrom {
			validPrimaryDisks = append(validPrimaryDisks, disk)
		}
	}

	// If no disk was marked as primary, but only one disk has been
	// defined for the virtual machine, automatically mark it as the
	// primary.
	if !primaryFound && len(validPrimaryDisks) == 1 {
		validPrimaryDisks[0].Primary = true
	}
}

// Validate validates the disks configurations
func (d Disks) Validate(opts ValidationOptions) error {
	var mErr *multierror.Error
	var primaryIdx []string

	for i, disk := range d {
		displayIdx := i + 1 // NOTE: Increment index so disk counts start at 1 for user
		errPrefix := fmt.Sprintf("disk[%d] -", displayIdx)

		if disk.Primary {
			primaryIdx = append(primaryIdx, fmt.Sprintf("%d", displayIdx))
		}

		if disk.BusType == "" {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s %w: BusType", errPrefix, ErrMissingAttribute))
		}

		if disk.Kind == "" {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s %w: Kind", errPrefix, ErrMissingAttribute))
		}

		if disk.Devname == "" {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s %w: Devname", errPrefix, ErrMissingAttribute))
		}

		if disk.Size != "" && !convert.ValidBytesString(disk.Size) {
			mErr = multierror.Append(mErr,
				fmt.Errorf("%s Size value is not valid - %q", errPrefix, disk.Size))
		}

		if disk.Source != nil && disk.Source.Image != "" {
			if !fileExists(disk.Source.Image) {
				mErr = multierror.Append(mErr,
					fmt.Errorf("%s %w: %s", errPrefix, ErrPathNotFound, disk.Source.Image))
			}
			if !opts.AllowedPath(disk.Source.Image) {
				mErr = multierror.Append(mErr,
					fmt.Errorf("%s %w: %s", errPrefix, ErrDisallowedPath, disk.Source.Image))
			}
		}
	}

	if len(primaryIdx) == 0 {
		mErr = multierror.Append(mErr, ErrNoPrimary)
	} else if len(primaryIdx) > 1 {
		mErr = multierror.Append(mErr, fmt.Errorf("%w (disks: %s)",
			ErrMultiplePrimary, strings.Join(primaryIdx, ", ")))
	}

	if mErr != nil {
		return mErr
	}

	return nil
}

// Prepare prepares the disk for usage, importing it into the storage pool. The
// name is used for volume naming. Using the task name is ideal.
func (d Disks) Prepare(name string, s storage.Storage) error {
	// Generate the volumes for the virtual machine
	for _, disk := range d {
		var pool storage.Pool
		var err error

		if disk.Pool != "" {
			if pool, err = s.GetPool(disk.Pool); err != nil {
				return err
			}
		} else {
			if pool, err = s.DefaultPool(); err != nil {
				return err
			}
		}
		volumeName := fmt.Sprintf("%s_%s.img", name, disk.Devname)
		opts := storage.Options{
			Chained: disk.Chained,
			Size:    convert.MustToBytes(disk.Size),
			Sparse:  disk.Sparse,
			Target: storage.Target{
				Format: disk.Format,
			},
		}

		if disk.Source != nil {
			opts.Source = storage.Source{
				Format:     disk.Source.Format,
				Path:       disk.Source.Image,
				Snapshot:   disk.Source.Snapshot,
				Volume:     disk.Source.Volume,
				Identifier: disk.Source.identifier,
			}

			// If the disk source has an image and the identifier was
			// not set, generate the identifier now
			// NOTE: this is only done if chained since the identifer
			// is not used otherwise.
			if disk.Source.identifier == "" && disk.Chained {
				id, err := generateIdentifier(disk.Source.Image)
				if err != nil {
					return err
				}
				opts.Source.Identifier = id
			}

			// If the size what not set, use the size of the image
			if disk.Size == "" && disk.Source.Image != "" {
				info, err := os.Stat(disk.Source.Image)
				if err != nil {
					return err
				}
				opts.Size = uint64(info.Size())
			}
		}

		vol, err := pool.AddVolume(volumeName, opts)
		if err != nil {
			return err
		}

		// If the format was already set by the pool,
		// prefer that value
		if vol.Format == "" {
			vol.Format = disk.Format
		}

		// Fill in extra volume information
		vol.Kind = disk.Kind
		vol.Driver = disk.Driver
		vol.DeviceName = disk.Devname
		vol.BusType = disk.BusType
		vol.Primary = disk.Primary

		// Set the volume for the disk
		disk.Volume = vol
	}

	return nil
}

// Volumes returns the storage volumes for the configured disks
func (d Disks) Volumes() []storage.Volume {
	vols := make([]storage.Volume, 0, len(d))
	for _, disk := range d {
		if disk.Volume != nil {
			vols = append(vols, *disk.Volume)
		}
	}

	return vols
}

// Copy makes a copy of the disks
func (d Disks) Copy() Disks {
	copy := make(Disks, len(d))
	for i, disk := range d {
		dc := *disk
		if disk.Source != nil {
			sc := *disk.Source
			dc.Source = &sc
		}
		if disk.Volume != nil {
			vc := *disk.Volume
			dc.Volume = &vc
		}
		copy[i] = &dc
	}

	return copy
}

// generateDevname generates the device name of the disk.
func (d Disks) generateDevname(disk *Disk, s storage.Storage) string {
	names := []string{}
	for _, existingDisk := range d {
		if existingDisk.Devname != "" {
			names = append(names, existingDisk.Devname)
		}
	}

	return s.GenerateDeviceName(disk.BusType, names)
}

// ConfigSpec returns the HCL specification for the disks configuration
func ConfigSpec() *hclspec.Spec {
	return configSpec
}

// generateIdentifier generates an identifier for a source file based
// on the checksum of the contents
func generateIdentifier(path string) (string, error) {
	hash := sha512.New()
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	if _, err := io.Copy(hash, f); err != nil {
		return "", err
	}

	return fmt.Sprintf("%s-%x.img", identifierPrefix, hash.Sum(nil)), nil
}

// fileExists checks if a file exists at the path
func fileExists(path string) bool {
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return false
	}
	return !info.IsDir()
}
