name: ci

on:
  push:

jobs:
  mod:
    name: "run go mod tidy"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/setup-golang@36878950ae8f21c1bc25accaf67a4df88c29b01d # v3.0.0
      - uses: ./.github/actions/install-libvirt-dev
      - name: "run go mod tidy"
        run: |
          make check-go-mod
  lint:
    name: "run lint"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/setup-golang@36878950ae8f21c1bc25accaf67a4df88c29b01d # v3.0.0
      - uses: ./.github/actions/install-libvirt-dev
      - name: "run lint"
        run: |
          make lint-tools
          make lint
  test:
    name: "run tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/setup-golang@36878950ae8f21c1bc25accaf67a4df88c29b01d # v3.0.0
      - uses: ./.github/actions/install-libvirt-dev
      - name: "run tests"
        run: |
          make test-tools
          make test
  build:
    name: "run build"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/setup-golang@36878950ae8f21c1bc25accaf67a4df88c29b01d # v3.0.0
      - uses: ./.github/actions/install-libvirt-dev
      - name: "run build"
        run: |
          make build
